# Generated by Django 5.1.2 on 2024-10-23 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
